### ISSUE TITLE
Modificar las coordenadas

### ISSUE THREAD

**Issue by angelmart** [angelmart/IWVG.SwC.JoseAngelSanchez#1]
Crear métodos para modificar las coordenadas en la clase Point.

[más información](https://github.com/angelmart/IWVG.SwC.JoseAngelSanchez/wiki/Point)

**Comment by DantDP** [comment]
@angelmart ya he añadido los métodos para este issue, y he probado los tests. Luego he subido la rama issue#01 y la develop actualizada. Cierro ticket.
