### ISSUE TITLE
Fracción equivalente.

### ISSUE THREAD

**Issue by angelmart** [angelmart/IWVG.SwC.JoseAngelSanchez#4]
Crear método que indique si una fracción es equivalente.

[más información](https://github.com/angelmart/IWVG.SwC.JoseAngelSanchez/wiki/Fraction)

**Comment by DantDP** [comment]
@angelmart pero una fracción es equivalente "respecto a otra", y la clase FRACTION tiene variables y constructor para una sola fracción. Un objeto creado con esta clase solo me da valores de **una** fracción (un denominador y un numerador), no de dos fracciones (dos numeradores y dos denominadores en total) que pueda comparar.
No entiendo cómo crear el método, tal y como viene definida la clase FRACTION

**Comment by angelmart** [comment]
Crearías un método con el siguiente esquema

isEquivalente( Fraction f2 )

La segunda fracción se la pasarías como parámetro de la función y para comparar usarías sentencias del tipo this.getX() == f2.getX().

Si no me he explicado bien, me indicas lo que no has entendido y si es necesario extiendo la respuesta.

**Comment by DantDP** [comment]
@angelmart ya he creado el método y su respectivo test lo he probado correctamente. Luego he subido la rama issue#04 y la develop actualizada. Cierro ticket.
