### ISSUE TITLE
Considerar denominadores negativos en isDecimal

### ISSUE THREAD

**Issue by angelmart** [angelmart/IWVG.SwC.JoseAngelSanchez#7]
En la actualidad, el código solamente considera denominadores positivos. Corregirlo para que aquellas fracciones con denominador = -10 devuelvan true al preguntarles si es decimal.

[más información](https://github.com/angelmart/IWVG.SwC.JoseAngelSanchez/wiki/Fraction)

**Comment by joaquinz916** [comment]
Corregido, ahora se toman en cuenta números negativos en denominador. Ticket cerrado
