### ISSUE TITLE
Simplificación del código (isEquivalent)

### ISSUE THREAD

**Issue by angelmart** [angelmart/IWVG.SwC.JoseAngelSanchez#8]
La función isEquivalent está bien, pero sería preferible si simplificases el código y así reducir los problemas que ha encontrado Sonarcloud.

Sustituir la estructura if-else por un único return.

**Comment by angelmart** [comment]
[más información](https://sonarcloud.io/project/issues?facetMode=effort&id=es.upm.miw%3AIWVG.SwC.JoseAngelSanchez&resolved=false&types=CODE_SMELL)

**Comment by DantDP** [comment]
@angelmart lo he hecho con if else porque la fracción puede ser o no ser equivalente. 
Ese return, ¿qué devuelve? Porque si devuelve si **sí es** o si **no es** equivalente, un método con if/else es adecuado. Además, en el test incluí ambos casos (en caso de que diera true y de que diera false).
La cobertura de análisis de Sonarcloud de tu repositorio es del 94,7%, y no es lo normal que sea tan elevada.

**Comment by DantDP** [comment]
@angelmart necesito una respuesta o aclaración antes de que expire el hito de este issue.

**Comment by DantDP** [comment]
@angelmart he modificado el return del método, que ya no devuelve true o false, sino si "Es equivalente" o "No es equivalente". Los test los he probado correctamente, y he incorporado la rama issue#08, así como estos cambios local al develop remoto.

**Comment by abernalf** [comment]
Yo he tenido el mismo problema que @DantDP y lo he solucionado de la siguiente manera:

Sustituyes el if/else por la sentencia que tienes en el if y la retornas, en tu caso quedaría tal que así:
`return (this.numerator * fraction2.denominator) == (this.denominator * fraction2.numerator)`

**Comment by angelmart** [comment]
@DantDP Lo has entendido mal. Como dije al introducir el ticket, el código de antes estaba bien y hacía lo que debía (devolver true o false). De hecho, devolver un String es complejidad innecesaria en este caso.

La solución es lo que ya ha mencionado Chinegua. Tendrías que modificarlo de nuevo y devolver directamente la sentencia que ha escrito Chinegua. Perdona que no lo haya mencionado, pero como Sonarcloud explicaba directamente lo que había que hacer no creí que fuese necesario.

Respondiendo a tu duda sobre Code Smell, en efecto, no es un error en el código, es solamente cuestión de lo fácil que sea entenderlo. Point lo he dejado porque es de la plantilla, preguntaré si debo arreglarlo.

**Comment by DantDP** [comment]
Ya he simplificado el método conforme a lo indicado, y el test funciona correctamente. Esta corrección se ha incorporado en una nueva rama (issue#10).
