### ISSUE TITLE
Simplicación de código en isUnitaria

### ISSUE THREAD

**Issue by angelmart** [angelmart/IWVG.SwC.JoseAngelSanchez#9]
La función isUnitaria está bien, pero sería preferible si simplificases el código y así reducir los problemas que ha encontrado Sonarcloud.

Sustituir la estructura if-else por un único return.

**Comment by abernalf** [comment]
Si me pasas el link de Sonar te lo agradezco para poder trabajar sobre ello

**Comment by angelmart** [comment]
[más información](https://sonarcloud.io/project/issues?facetMode=effort&id=es.upm.miw%3AIWVG.SwC.JoseAngelSanchez&resolved=false&types=CODE_SMELL)

**Comment by abernalf** [comment]
Done
